---
title: "Answers"
---

# Sara 1

## Variables

### Permanency

1.  What level of measurement would the variable in the dataset have? Nominal
2.  She knows she needs to examine the distribution of the above variable but which techniques would be best? Frequency tables and bar charts are useful for showing the distribution of nominal variables

### Job satisfaction

1.  What level of measurement does it have? Ordinal; cases are distributed across categories and the categories have an order (i.e. they are more or less satisfied).
2.  Which of the following techniques can be used to examine the distribution of responses? You can use a frequency table and bar chart to show the distribution across categories. Median and mean can be calculated but may be difficult to interpret. There is a debate about whether we should ever calculate the mean of ordinal variables.

### Hours worked

1.  What level of measurement is it? Scale/continuous
2.  What type of figure is presented above? Histogram
3.  How can we describe the distribution? The variable distribution is approaching normal but with a negative/left skew as people are concentrated at higher values.

# Sara 2

## What techniques?

1.  Sarah works on her research questions and starts to think about the techniques can she use. For each of the research questions below, select an appropriate method of exploring the relationship.

-   a\. Is there any gender difference in permanent employment?

-   b\. Is job permanency related to usual hours worked (i.e. are those in non-permanent jobs likely to work more hours)?

-   c\. Do those with a permanent job report higher levels of job satisfaction?
