---
title: "Adding more variables in a hierarchical approach"
---

## Context

Marcos has created three models in a hierarchical approach. He wants to know how employee perceptions of their work including a sense of achievement and a sense of time to get things done relates to work stress.

-   Model 1 is the model presented above.

-   Model 2 includes the same as model 1 plus dummy variables indicated sense of achievement.

-   Model 3 adds a further variable for the feeling of time to get things done.

## Model summary

Here is the model summary information for the three variables.

1.  The improvement in the variance explained is greatest between model 1 and model 2. Is this statement, true or false?

2.  Model 3 accounts for 17 percent of the variation in feeling worried. Is this true or False?

+-------+---------+----------+-------------------+------------------------------+
| Model | R       | R Square | Adjusted R Square | Std. Error of the Estimate   |
+-------+---------+----------+-------------------+------------------------------+
| 1     | .180^a^ | .032     | .032              | .971                         |
+-------+---------+----------+-------------------+------------------------------+
| 2     | .243^b^ | .059     | .059              | .957                         |
+-------+---------+----------+-------------------+------------------------------+
| 3     | .414^c^ | .171     | .171              | .898                         |
+-------+---------+----------+-------------------+------------------------------+

## Model coefficients

The coefficients of the model are below. Using the information below and above, write 3 sentences to summarise the model results.

+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
|                                                                            | B     | Std. Error | Beta  | t       | Sig. |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| **Model 1**                                                                |       |            |       |         |      |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| Intercept                                                                  | 3.698 | .018       |       | 205.330 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| years working at this  workplace                                           | -.012 | .005       | -.017 | -2.487  | .013 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| male                                                                       | .090  | .013       | .045  | 6.671   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| supervisor                                                                 | -.363 | .014       | -.175 | -25.446 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| **Model 2**                                                                |       |            |       |         |      |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| (Constant)                                                                 | 3.667 | .022       |       | 164.146 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| years working at this  workplace                                           | -.010 | .005       | -.013 | -1.976  | .048 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| male                                                                       | .107  | .013       | .054  | 8.019   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| supervisor                                                                 | -.391 | .014       | -.189 | -27.576 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| No sense of achievement (baseline neutral)                                 | -.437 | .025       | -.135 | -17.259 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| Sense of achievement (baseline neutral)                                    | .100  | .017       | .047  | 5.892   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| **Model 3**                                                                |       |            |       |         |      |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| (Constant)                                                                 | 2.676 | .028       |       | 95.636  | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| years working at this  workplace                                           | .019  | .005       | .026  | 4.070   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| male                                                                       | .073  | .013       | .037  | 5.798   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| supervisor                                                                 | -.242 | .014       | -.117 | -17.827 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| No sense of achievement (baseline neutral)                                 | -.355 | .024       | -.110 | -14.892 | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| Sense of achievement (baseline neutral)                                    | .084  | .016       | .039  | 5.267   | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
| never seem to have enough time to get work done (low score=more agreement) | .315  | .006       | .347  | 53.494  | .000 |
+----------------------------------------------------------------------------+-------+------------+-------+---------+------+
